# Generated by Django 3.2.3 on 2021-09-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cinemas',
            fields=[
                ('cine_id', models.AutoField(primary_key=True, serialize=False)),
                ('cine_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('current_movies', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cinemas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.IntegerField(blank=True, null=True)),
                ('member_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('member_pw', models.CharField(blank=True, max_length=255, null=True)),
                ('member_name', models.CharField(blank=True, max_length=255, null=True)),
                ('member_tel', models.CharField(blank=True, max_length=255, null=True)),
                ('resident_num', models.CharField(blank=True, max_length=255, null=True)),
                ('birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('like_genre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'members',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(blank=True, max_length=255, null=True)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('actor', models.CharField(blank=True, max_length=255, null=True)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('age_limit', models.CharField(blank=True, max_length=255, null=True)),
                ('story', models.TextField(blank=True, null=True)),
                ('open_date', models.DateField(blank=True, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('poster_src', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'movies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(blank=True, max_length=255, null=True)),
                ('house_num', models.CharField(blank=True, max_length=255, null=True)),
                ('movie_time', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'movie_schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieSchedules',
            fields=[
                ('schedule_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cine_name', models.CharField(blank=True, max_length=255, null=True)),
                ('movie_name', models.CharField(blank=True, max_length=255, null=True)),
                ('house_num', models.CharField(blank=True, max_length=255, null=True)),
                ('movie_time', models.CharField(blank=True, max_length=255, null=True)),
                ('movie_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movie_schedules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MymovieRe',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('re_pw', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('cont', models.TextField(blank=True, null=True)),
                ('like_genre', models.CharField(blank=True, max_length=255, null=True)),
                ('bip', models.CharField(blank=True, max_length=255, null=True)),
                ('bdate', models.DateTimeField(blank=True, null=True)),
                ('readcnt', models.IntegerField(blank=True, null=True)),
                ('gnum', models.IntegerField(blank=True, null=True)),
                ('onum', models.IntegerField(blank=True, null=True)),
                ('nested', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mymovie_re',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nonmembers',
            fields=[
                ('nm_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nm_birth', models.DateField(blank=True, null=True)),
                ('nm_tel', models.CharField(blank=True, max_length=255, null=True)),
                ('nm_pw', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nonmembers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbid', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.CharField(blank=True, max_length=100, null=True)),
                ('shampoo_count', models.CharField(blank=True, max_length=100, null=True)),
                ('now_hair', models.CharField(blank=True, max_length=100, null=True)),
                ('hair_product', models.CharField(blank=True, max_length=100, null=True)),
                ('perm', models.CharField(blank=True, max_length=100, null=True)),
                ('color_count', models.CharField(blank=True, max_length=100, null=True)),
                ('shampoo_buy', models.CharField(blank=True, max_length=100, null=True)),
                ('product_want', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'finaldb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ticket_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ticket_date', models.DateTimeField(blank=True, null=True)),
                ('cine_name', models.CharField(blank=True, max_length=255, null=True)),
                ('seat', models.CharField(blank=True, max_length=255, null=True)),
                ('movie_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tickets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketsNm',
            fields=[
                ('ticket_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ticket_date', models.DateTimeField(blank=True, null=True)),
                ('cine_name', models.CharField(blank=True, max_length=255, null=True)),
                ('seat', models.CharField(blank=True, max_length=255, null=True)),
                ('movie_id', models.IntegerField(blank=True, null=True)),
                ('movie_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tickets_nm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Voc',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('voc_pw', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('cont', models.TextField(blank=True, null=True)),
                ('voc_type', models.CharField(blank=True, max_length=255, null=True)),
                ('bip', models.CharField(blank=True, max_length=255, null=True)),
                ('bdate', models.DateTimeField(blank=True, null=True)),
                ('readcnt', models.IntegerField(blank=True, null=True)),
                ('gnum', models.IntegerField(blank=True, null=True)),
                ('onum', models.IntegerField(blank=True, null=True)),
                ('nested', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'voc',
                'managed': False,
            },
        ),
    ]
