# Generated by Django 3.2.3 on 2021-09-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finaldb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbid', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.CharField(blank=True, max_length=100, null=True)),
                ('shampoo_count', models.CharField(blank=True, max_length=100, null=True)),
                ('now_hair', models.CharField(blank=True, max_length=100, null=True)),
                ('hair_product', models.CharField(blank=True, max_length=100, null=True)),
                ('perm', models.CharField(blank=True, max_length=100, null=True)),
                ('color_count', models.CharField(blank=True, max_length=100, null=True)),
                ('shampoo_buy', models.CharField(blank=True, max_length=100, null=True)),
                ('product_want', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'finaldb',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
